# Part1: Data Pre-processing

In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  

In [2]:
dataset=pd.read_csv("C:\\Users\\surya\\Downloads\\data-set\\Churn_Modelling.csv")  

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
dataset.shape

(10000, 14)

In [6]:
X=dataset.iloc[:, 3:13].values  

In [16]:
y=dataset.iloc[:, 13].values  

In [17]:
X

array([[228, 'France', 'Female', ..., 1, 1, 101348.88],
       [217, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [111, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [318, 'France', 'Female', ..., 0, 1, 42085.58],
       [381, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [401, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [18]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [25]:
from sklearn.preprocessing import LabelEncoder  
labelencoder_X=LabelEncoder()  
X[:,0]=labelencoder_X.fit_transform(X[:,0])  

In [26]:
labelencoder_X_1=LabelEncoder()  
X[:, 1]=labelencoder_X_1.fit_transform(X[:, 1])  

In [29]:
labelencoder_X_2=LabelEncoder()  
X[:,2]=labelencoder_X_2.fit_transform(X[:, 2]) 

In [30]:
from sklearn.compose import ColumnTransformer  
label_encoder_x_1=LabelEncoder()  
X[: ,2]=label_encoder_x_1.fit_transform(X[:,2])  
transformer=ColumnTransformer(  
    transformers=[  
        ("OneHot",        # Just a name  
         OneHotEncoder(), # The transformer class  
         [1]              # The column(s) to be applied on.  
         )  
    ],  
    remainder='passthrough' # don't apply anything to the remaining columns   
)  
X=transformer.fit_transform(X.tolist())  
X=X.astype('float64')  

In [31]:
X=X[:, 1:]  

In [32]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)  

In [33]:
X_train

array([[0.0000000e+00, 1.0000000e+00, 2.7600000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.6383064e+05],
       [1.0000000e+00, 0.0000000e+00, 3.6000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 5.7098000e+04],
       [0.0000000e+00, 0.0000000e+00, 1.4400000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8563076e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 3.4700000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 1.9900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 2.3200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [34]:
from sklearn.preprocessing import StandardScaler  
sc=StandardScaler()  
X_train=sc.fit_transform(X_train)  
X_test=sc.transform(X_test)  

# Part2: Building an ANN

In [37]:
import keras   

In [38]:
from keras.models import Sequential  
from keras.layers import Dense  

In [39]:
classifier=Sequential() 

In [40]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim = 11))  

In [41]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation = 'relu'))

In [43]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid')) 

In [44]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])  

In [45]:
classifier.fit(X_train,y_train,batch_size=10,epochs=100) 

Epoch 1/100
800/800 [==============================] - 5s 4ms/step - loss: 0.4878 - accuracy: 0.7955
Epoch 2/100
800/800 [==============================] - 4s 4ms/step - loss: 0.4267 - accuracy: 0.7962
Epoch 3/100
800/800 [==============================] - 4s 5ms/step - loss: 0.4195 - accuracy: 0.8242
Epoch 4/100
800/800 [==============================] - 4s 5ms/step - loss: 0.4127 - accuracy: 0.8321
Epoch 5/100
800/800 [==============================] - 4s 5ms/step - loss: 0.4077 - accuracy: 0.8334
Epoch 6/100
800/800 [==============================] - 4s 5ms/step - loss: 0.4045 - accuracy: 0.8354
Epoch 7/100
800/800 [==============================] - 4s 5ms/step - loss: 0.4026 - accuracy: 0.8344
Epoch 8/100
800/800 [==============================] - 4s 5ms/step - loss: 0.4012 - accuracy: 0.8345
Epoch 9/100
800/800 [==============================] - 5s 7ms/step - loss: 0.4000 - accuracy: 0.8351
Epoch 10/100
800/800 [==============================] - 6s 7ms/step - loss: 0.3986 - accura

800/800 [==============================] - 4s 5ms/step - loss: 0.3423 - accuracy: 0.8587
Epoch 82/100
800/800 [==============================] - 4s 5ms/step - loss: 0.3414 - accuracy: 0.8595
Epoch 83/100
800/800 [==============================] - 4s 5ms/step - loss: 0.3418 - accuracy: 0.8584
Epoch 84/100
800/800 [==============================] - 4s 4ms/step - loss: 0.3403 - accuracy: 0.8599
Epoch 85/100
800/800 [==============================] - 4s 4ms/step - loss: 0.3408 - accuracy: 0.8615
Epoch 86/100
800/800 [==============================] - 4s 5ms/step - loss: 0.3408 - accuracy: 0.8574
Epoch 87/100
800/800 [==============================] - 4s 4ms/step - loss: 0.3411 - accuracy: 0.8612
Epoch 88/100
800/800 [==============================] - 4s 5ms/step - loss: 0.3413 - accuracy: 0.8599
Epoch 89/100
800/800 [==============================] - 4s 5ms/step - loss: 0.3406 - accuracy: 0.8587
Epoch 90/100
800/800 [==============================] - 4s 5ms/step - loss: 0.3415 - accuracy: 

# Part3: Making the Predictions and Evaluating the Model

In [46]:
y_pred=classifier.predict(X_test) 

63/63 [==============================] - 1s 4ms/step


In [47]:
y_pred

array([[0.24620707],
       [0.2893916 ],
       [0.12732305],
       ...,
       [0.16310292],
       [0.16529898],
       [0.28225496]], dtype=float32)

In [48]:
y_pred=(y_pred > 0.5)   

In [49]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
from sklearn.metrics import confusion_matrix  
cm=confusion_matrix(y_test, y_pred)  